// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smile/smile.proto

package smile;

public final class Smile {
  private Smile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TempoSampleUpdateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smile.TempoSampleUpdateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    java.util.List<smile.Smile.TempoSample> 
        getTempoSamplesList();
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    smile.Smile.TempoSample getTempoSamples(int index);
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    int getTempoSamplesCount();
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    java.util.List<? extends smile.Smile.TempoSampleOrBuilder> 
        getTempoSamplesOrBuilderList();
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    smile.Smile.TempoSampleOrBuilder getTempoSamplesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code smile.TempoSampleUpdateMessage}
   */
  public static final class TempoSampleUpdateMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smile.TempoSampleUpdateMessage)
      TempoSampleUpdateMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TempoSampleUpdateMessage.newBuilder() to construct.
    private TempoSampleUpdateMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TempoSampleUpdateMessage() {
      tempoSamples_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TempoSampleUpdateMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TempoSampleUpdateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tempoSamples_ = new java.util.ArrayList<smile.Smile.TempoSample>();
                mutable_bitField0_ |= 0x00000001;
              }
              tempoSamples_.add(
                  input.readMessage(smile.Smile.TempoSample.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tempoSamples_ = java.util.Collections.unmodifiableList(tempoSamples_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smile.Smile.internal_static_smile_TempoSampleUpdateMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smile.Smile.internal_static_smile_TempoSampleUpdateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smile.Smile.TempoSampleUpdateMessage.class, smile.Smile.TempoSampleUpdateMessage.Builder.class);
    }

    public static final int TEMPOSAMPLES_FIELD_NUMBER = 1;
    private java.util.List<smile.Smile.TempoSample> tempoSamples_;
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public java.util.List<smile.Smile.TempoSample> getTempoSamplesList() {
      return tempoSamples_;
    }
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends smile.Smile.TempoSampleOrBuilder> 
        getTempoSamplesOrBuilderList() {
      return tempoSamples_;
    }
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public int getTempoSamplesCount() {
      return tempoSamples_.size();
    }
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public smile.Smile.TempoSample getTempoSamples(int index) {
      return tempoSamples_.get(index);
    }
    /**
     * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public smile.Smile.TempoSampleOrBuilder getTempoSamplesOrBuilder(
        int index) {
      return tempoSamples_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tempoSamples_.size(); i++) {
        output.writeMessage(1, tempoSamples_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tempoSamples_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tempoSamples_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smile.Smile.TempoSampleUpdateMessage)) {
        return super.equals(obj);
      }
      smile.Smile.TempoSampleUpdateMessage other = (smile.Smile.TempoSampleUpdateMessage) obj;

      if (!getTempoSamplesList()
          .equals(other.getTempoSamplesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTempoSamplesCount() > 0) {
        hash = (37 * hash) + TEMPOSAMPLES_FIELD_NUMBER;
        hash = (53 * hash) + getTempoSamplesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smile.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smile.Smile.TempoSampleUpdateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smile.TempoSampleUpdateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smile.TempoSampleUpdateMessage)
        smile.Smile.TempoSampleUpdateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smile.Smile.internal_static_smile_TempoSampleUpdateMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smile.Smile.internal_static_smile_TempoSampleUpdateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smile.Smile.TempoSampleUpdateMessage.class, smile.Smile.TempoSampleUpdateMessage.Builder.class);
      }

      // Construct using smile.Smile.TempoSampleUpdateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTempoSamplesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (tempoSamplesBuilder_ == null) {
          tempoSamples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tempoSamplesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smile.Smile.internal_static_smile_TempoSampleUpdateMessage_descriptor;
      }

      @java.lang.Override
      public smile.Smile.TempoSampleUpdateMessage getDefaultInstanceForType() {
        return smile.Smile.TempoSampleUpdateMessage.getDefaultInstance();
      }

      @java.lang.Override
      public smile.Smile.TempoSampleUpdateMessage build() {
        smile.Smile.TempoSampleUpdateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smile.Smile.TempoSampleUpdateMessage buildPartial() {
        smile.Smile.TempoSampleUpdateMessage result = new smile.Smile.TempoSampleUpdateMessage(this);
        int from_bitField0_ = bitField0_;
        if (tempoSamplesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tempoSamples_ = java.util.Collections.unmodifiableList(tempoSamples_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tempoSamples_ = tempoSamples_;
        } else {
          result.tempoSamples_ = tempoSamplesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smile.Smile.TempoSampleUpdateMessage) {
          return mergeFrom((smile.Smile.TempoSampleUpdateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smile.Smile.TempoSampleUpdateMessage other) {
        if (other == smile.Smile.TempoSampleUpdateMessage.getDefaultInstance()) return this;
        if (tempoSamplesBuilder_ == null) {
          if (!other.tempoSamples_.isEmpty()) {
            if (tempoSamples_.isEmpty()) {
              tempoSamples_ = other.tempoSamples_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTempoSamplesIsMutable();
              tempoSamples_.addAll(other.tempoSamples_);
            }
            onChanged();
          }
        } else {
          if (!other.tempoSamples_.isEmpty()) {
            if (tempoSamplesBuilder_.isEmpty()) {
              tempoSamplesBuilder_.dispose();
              tempoSamplesBuilder_ = null;
              tempoSamples_ = other.tempoSamples_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tempoSamplesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTempoSamplesFieldBuilder() : null;
            } else {
              tempoSamplesBuilder_.addAllMessages(other.tempoSamples_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smile.Smile.TempoSampleUpdateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smile.Smile.TempoSampleUpdateMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<smile.Smile.TempoSample> tempoSamples_ =
        java.util.Collections.emptyList();
      private void ensureTempoSamplesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tempoSamples_ = new java.util.ArrayList<smile.Smile.TempoSample>(tempoSamples_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          smile.Smile.TempoSample, smile.Smile.TempoSample.Builder, smile.Smile.TempoSampleOrBuilder> tempoSamplesBuilder_;

      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public java.util.List<smile.Smile.TempoSample> getTempoSamplesList() {
        if (tempoSamplesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tempoSamples_);
        } else {
          return tempoSamplesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public int getTempoSamplesCount() {
        if (tempoSamplesBuilder_ == null) {
          return tempoSamples_.size();
        } else {
          return tempoSamplesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public smile.Smile.TempoSample getTempoSamples(int index) {
        if (tempoSamplesBuilder_ == null) {
          return tempoSamples_.get(index);
        } else {
          return tempoSamplesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder setTempoSamples(
          int index, smile.Smile.TempoSample value) {
        if (tempoSamplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTempoSamplesIsMutable();
          tempoSamples_.set(index, value);
          onChanged();
        } else {
          tempoSamplesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder setTempoSamples(
          int index, smile.Smile.TempoSample.Builder builderForValue) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.set(index, builderForValue.build());
          onChanged();
        } else {
          tempoSamplesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(smile.Smile.TempoSample value) {
        if (tempoSamplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(value);
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(
          int index, smile.Smile.TempoSample value) {
        if (tempoSamplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(index, value);
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(
          smile.Smile.TempoSample.Builder builderForValue) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(builderForValue.build());
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(
          int index, smile.Smile.TempoSample.Builder builderForValue) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(index, builderForValue.build());
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder addAllTempoSamples(
          java.lang.Iterable<? extends smile.Smile.TempoSample> values) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tempoSamples_);
          onChanged();
        } else {
          tempoSamplesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder clearTempoSamples() {
        if (tempoSamplesBuilder_ == null) {
          tempoSamples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tempoSamplesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public Builder removeTempoSamples(int index) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.remove(index);
          onChanged();
        } else {
          tempoSamplesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public smile.Smile.TempoSample.Builder getTempoSamplesBuilder(
          int index) {
        return getTempoSamplesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public smile.Smile.TempoSampleOrBuilder getTempoSamplesOrBuilder(
          int index) {
        if (tempoSamplesBuilder_ == null) {
          return tempoSamples_.get(index);  } else {
          return tempoSamplesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public java.util.List<? extends smile.Smile.TempoSampleOrBuilder> 
           getTempoSamplesOrBuilderList() {
        if (tempoSamplesBuilder_ != null) {
          return tempoSamplesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tempoSamples_);
        }
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public smile.Smile.TempoSample.Builder addTempoSamplesBuilder() {
        return getTempoSamplesFieldBuilder().addBuilder(
            smile.Smile.TempoSample.getDefaultInstance());
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public smile.Smile.TempoSample.Builder addTempoSamplesBuilder(
          int index) {
        return getTempoSamplesFieldBuilder().addBuilder(
            index, smile.Smile.TempoSample.getDefaultInstance());
      }
      /**
       * <code>repeated .smile.TempoSample tempoSamples = 1;</code>
       */
      public java.util.List<smile.Smile.TempoSample.Builder> 
           getTempoSamplesBuilderList() {
        return getTempoSamplesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          smile.Smile.TempoSample, smile.Smile.TempoSample.Builder, smile.Smile.TempoSampleOrBuilder> 
          getTempoSamplesFieldBuilder() {
        if (tempoSamplesBuilder_ == null) {
          tempoSamplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              smile.Smile.TempoSample, smile.Smile.TempoSample.Builder, smile.Smile.TempoSampleOrBuilder>(
                  tempoSamples_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tempoSamples_ = null;
        }
        return tempoSamplesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smile.TempoSampleUpdateMessage)
    }

    // @@protoc_insertion_point(class_scope:smile.TempoSampleUpdateMessage)
    private static final smile.Smile.TempoSampleUpdateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smile.Smile.TempoSampleUpdateMessage();
    }

    public static smile.Smile.TempoSampleUpdateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TempoSampleUpdateMessage>
        PARSER = new com.google.protobuf.AbstractParser<TempoSampleUpdateMessage>() {
      @java.lang.Override
      public TempoSampleUpdateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TempoSampleUpdateMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TempoSampleUpdateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TempoSampleUpdateMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smile.Smile.TempoSampleUpdateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TempoSampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smile.TempoSample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string igoId = 1;</code>
     * @return The igoId.
     */
    java.lang.String getIgoId();
    /**
     * <code>string igoId = 1;</code>
     * @return The bytes for igoId.
     */
    com.google.protobuf.ByteString
        getIgoIdBytes();

    /**
     * <code>string cmoId = 2;</code>
     * @return The cmoId.
     */
    java.lang.String getCmoId();
    /**
     * <code>string cmoId = 2;</code>
     * @return The bytes for cmoId.
     */
    com.google.protobuf.ByteString
        getCmoIdBytes();

    /**
     * <code>bool embargoStatus = 3;</code>
     * @return The embargoStatus.
     */
    boolean getEmbargoStatus();

    /**
     * <code>string custodian = 4;</code>
     * @return The custodian.
     */
    java.lang.String getCustodian();
    /**
     * <code>string custodian = 4;</code>
     * @return The bytes for custodian.
     */
    com.google.protobuf.ByteString
        getCustodianBytes();
  }
  /**
   * Protobuf type {@code smile.TempoSample}
   */
  public static final class TempoSample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smile.TempoSample)
      TempoSampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TempoSample.newBuilder() to construct.
    private TempoSample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TempoSample() {
      igoId_ = "";
      cmoId_ = "";
      custodian_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TempoSample();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TempoSample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              igoId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cmoId_ = s;
              break;
            }
            case 24: {

              embargoStatus_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              custodian_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smile.Smile.internal_static_smile_TempoSample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smile.Smile.internal_static_smile_TempoSample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smile.Smile.TempoSample.class, smile.Smile.TempoSample.Builder.class);
    }

    public static final int IGOID_FIELD_NUMBER = 1;
    private volatile java.lang.Object igoId_;
    /**
     * <code>string igoId = 1;</code>
     * @return The igoId.
     */
    @java.lang.Override
    public java.lang.String getIgoId() {
      java.lang.Object ref = igoId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        igoId_ = s;
        return s;
      }
    }
    /**
     * <code>string igoId = 1;</code>
     * @return The bytes for igoId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIgoIdBytes() {
      java.lang.Object ref = igoId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        igoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMOID_FIELD_NUMBER = 2;
    private volatile java.lang.Object cmoId_;
    /**
     * <code>string cmoId = 2;</code>
     * @return The cmoId.
     */
    @java.lang.Override
    public java.lang.String getCmoId() {
      java.lang.Object ref = cmoId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmoId_ = s;
        return s;
      }
    }
    /**
     * <code>string cmoId = 2;</code>
     * @return The bytes for cmoId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmoIdBytes() {
      java.lang.Object ref = cmoId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMBARGOSTATUS_FIELD_NUMBER = 3;
    private boolean embargoStatus_;
    /**
     * <code>bool embargoStatus = 3;</code>
     * @return The embargoStatus.
     */
    @java.lang.Override
    public boolean getEmbargoStatus() {
      return embargoStatus_;
    }

    public static final int CUSTODIAN_FIELD_NUMBER = 4;
    private volatile java.lang.Object custodian_;
    /**
     * <code>string custodian = 4;</code>
     * @return The custodian.
     */
    @java.lang.Override
    public java.lang.String getCustodian() {
      java.lang.Object ref = custodian_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        custodian_ = s;
        return s;
      }
    }
    /**
     * <code>string custodian = 4;</code>
     * @return The bytes for custodian.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustodianBytes() {
      java.lang.Object ref = custodian_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        custodian_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(igoId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, igoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmoId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmoId_);
      }
      if (embargoStatus_ != false) {
        output.writeBool(3, embargoStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(custodian_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, custodian_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(igoId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, igoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmoId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmoId_);
      }
      if (embargoStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, embargoStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(custodian_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, custodian_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smile.Smile.TempoSample)) {
        return super.equals(obj);
      }
      smile.Smile.TempoSample other = (smile.Smile.TempoSample) obj;

      if (!getIgoId()
          .equals(other.getIgoId())) return false;
      if (!getCmoId()
          .equals(other.getCmoId())) return false;
      if (getEmbargoStatus()
          != other.getEmbargoStatus()) return false;
      if (!getCustodian()
          .equals(other.getCustodian())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IGOID_FIELD_NUMBER;
      hash = (53 * hash) + getIgoId().hashCode();
      hash = (37 * hash) + CMOID_FIELD_NUMBER;
      hash = (53 * hash) + getCmoId().hashCode();
      hash = (37 * hash) + EMBARGOSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEmbargoStatus());
      hash = (37 * hash) + CUSTODIAN_FIELD_NUMBER;
      hash = (53 * hash) + getCustodian().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smile.Smile.TempoSample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smile.Smile.TempoSample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smile.Smile.TempoSample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smile.Smile.TempoSample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smile.Smile.TempoSample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smile.Smile.TempoSample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smile.Smile.TempoSample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smile.Smile.TempoSample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smile.Smile.TempoSample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smile.Smile.TempoSample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smile.Smile.TempoSample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smile.Smile.TempoSample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smile.Smile.TempoSample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smile.TempoSample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smile.TempoSample)
        smile.Smile.TempoSampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smile.Smile.internal_static_smile_TempoSample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smile.Smile.internal_static_smile_TempoSample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smile.Smile.TempoSample.class, smile.Smile.TempoSample.Builder.class);
      }

      // Construct using smile.Smile.TempoSample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        igoId_ = "";

        cmoId_ = "";

        embargoStatus_ = false;

        custodian_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smile.Smile.internal_static_smile_TempoSample_descriptor;
      }

      @java.lang.Override
      public smile.Smile.TempoSample getDefaultInstanceForType() {
        return smile.Smile.TempoSample.getDefaultInstance();
      }

      @java.lang.Override
      public smile.Smile.TempoSample build() {
        smile.Smile.TempoSample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smile.Smile.TempoSample buildPartial() {
        smile.Smile.TempoSample result = new smile.Smile.TempoSample(this);
        result.igoId_ = igoId_;
        result.cmoId_ = cmoId_;
        result.embargoStatus_ = embargoStatus_;
        result.custodian_ = custodian_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smile.Smile.TempoSample) {
          return mergeFrom((smile.Smile.TempoSample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smile.Smile.TempoSample other) {
        if (other == smile.Smile.TempoSample.getDefaultInstance()) return this;
        if (!other.getIgoId().isEmpty()) {
          igoId_ = other.igoId_;
          onChanged();
        }
        if (!other.getCmoId().isEmpty()) {
          cmoId_ = other.cmoId_;
          onChanged();
        }
        if (other.getEmbargoStatus() != false) {
          setEmbargoStatus(other.getEmbargoStatus());
        }
        if (!other.getCustodian().isEmpty()) {
          custodian_ = other.custodian_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smile.Smile.TempoSample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smile.Smile.TempoSample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object igoId_ = "";
      /**
       * <code>string igoId = 1;</code>
       * @return The igoId.
       */
      public java.lang.String getIgoId() {
        java.lang.Object ref = igoId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          igoId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string igoId = 1;</code>
       * @return The bytes for igoId.
       */
      public com.google.protobuf.ByteString
          getIgoIdBytes() {
        java.lang.Object ref = igoId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          igoId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string igoId = 1;</code>
       * @param value The igoId to set.
       * @return This builder for chaining.
       */
      public Builder setIgoId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        igoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string igoId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIgoId() {
        
        igoId_ = getDefaultInstance().getIgoId();
        onChanged();
        return this;
      }
      /**
       * <code>string igoId = 1;</code>
       * @param value The bytes for igoId to set.
       * @return This builder for chaining.
       */
      public Builder setIgoIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        igoId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmoId_ = "";
      /**
       * <code>string cmoId = 2;</code>
       * @return The cmoId.
       */
      public java.lang.String getCmoId() {
        java.lang.Object ref = cmoId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmoId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmoId = 2;</code>
       * @return The bytes for cmoId.
       */
      public com.google.protobuf.ByteString
          getCmoIdBytes() {
        java.lang.Object ref = cmoId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmoId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmoId = 2;</code>
       * @param value The cmoId to set.
       * @return This builder for chaining.
       */
      public Builder setCmoId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmoId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmoId() {
        
        cmoId_ = getDefaultInstance().getCmoId();
        onChanged();
        return this;
      }
      /**
       * <code>string cmoId = 2;</code>
       * @param value The bytes for cmoId to set.
       * @return This builder for chaining.
       */
      public Builder setCmoIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmoId_ = value;
        onChanged();
        return this;
      }

      private boolean embargoStatus_ ;
      /**
       * <code>bool embargoStatus = 3;</code>
       * @return The embargoStatus.
       */
      @java.lang.Override
      public boolean getEmbargoStatus() {
        return embargoStatus_;
      }
      /**
       * <code>bool embargoStatus = 3;</code>
       * @param value The embargoStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEmbargoStatus(boolean value) {
        
        embargoStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool embargoStatus = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmbargoStatus() {
        
        embargoStatus_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object custodian_ = "";
      /**
       * <code>string custodian = 4;</code>
       * @return The custodian.
       */
      public java.lang.String getCustodian() {
        java.lang.Object ref = custodian_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          custodian_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string custodian = 4;</code>
       * @return The bytes for custodian.
       */
      public com.google.protobuf.ByteString
          getCustodianBytes() {
        java.lang.Object ref = custodian_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          custodian_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string custodian = 4;</code>
       * @param value The custodian to set.
       * @return This builder for chaining.
       */
      public Builder setCustodian(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        custodian_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string custodian = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustodian() {
        
        custodian_ = getDefaultInstance().getCustodian();
        onChanged();
        return this;
      }
      /**
       * <code>string custodian = 4;</code>
       * @param value The bytes for custodian to set.
       * @return This builder for chaining.
       */
      public Builder setCustodianBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        custodian_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smile.TempoSample)
    }

    // @@protoc_insertion_point(class_scope:smile.TempoSample)
    private static final smile.Smile.TempoSample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smile.Smile.TempoSample();
    }

    public static smile.Smile.TempoSample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TempoSample>
        PARSER = new com.google.protobuf.AbstractParser<TempoSample>() {
      @java.lang.Override
      public TempoSample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TempoSample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TempoSample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TempoSample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smile.Smile.TempoSample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smile_TempoSampleUpdateMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smile_TempoSampleUpdateMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smile_TempoSample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smile_TempoSample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021smile/smile.proto\022\005smile\"D\n\030TempoSampl" +
      "eUpdateMessage\022(\n\014tempoSamples\030\001 \003(\0132\022.s" +
      "mile.TempoSample\"U\n\013TempoSample\022\r\n\005igoId" +
      "\030\001 \001(\t\022\r\n\005cmoId\030\002 \001(\t\022\025\n\rembargoStatus\030\003" +
      " \001(\010\022\021\n\tcustodian\030\004 \001(\tB*Z(github.com/ms" +
      "kcc/mskprotobuf/smile;smileb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_smile_TempoSampleUpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smile_TempoSampleUpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smile_TempoSampleUpdateMessage_descriptor,
        new java.lang.String[] { "TempoSamples", });
    internal_static_smile_TempoSample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smile_TempoSample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smile_TempoSample_descriptor,
        new java.lang.String[] { "IgoId", "CmoId", "EmbargoStatus", "Custodian", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
