/*
Genome Nexus API

This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genome_nexus_public_api

import (
	"encoding/json"
)

// PtmFilter struct for PtmFilter
type PtmFilter struct {
	// List of Ensembl transcript IDs. For example [\"ENST00000361390\", \"ENST00000361453\", \"ENST00000361624\"]
	TranscriptIds []string `json:"transcriptIds,omitempty"`
}

// NewPtmFilter instantiates a new PtmFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPtmFilter() *PtmFilter {
	this := PtmFilter{}
	return &this
}

// NewPtmFilterWithDefaults instantiates a new PtmFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPtmFilterWithDefaults() *PtmFilter {
	this := PtmFilter{}
	return &this
}

// GetTranscriptIds returns the TranscriptIds field value if set, zero value otherwise.
func (o *PtmFilter) GetTranscriptIds() []string {
	if o == nil || isNil(o.TranscriptIds) {
		var ret []string
		return ret
	}
	return o.TranscriptIds
}

// GetTranscriptIdsOk returns a tuple with the TranscriptIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PtmFilter) GetTranscriptIdsOk() ([]string, bool) {
	if o == nil || isNil(o.TranscriptIds) {
    return nil, false
	}
	return o.TranscriptIds, true
}

// HasTranscriptIds returns a boolean if a field has been set.
func (o *PtmFilter) HasTranscriptIds() bool {
	if o != nil && !isNil(o.TranscriptIds) {
		return true
	}

	return false
}

// SetTranscriptIds gets a reference to the given []string and assigns it to the TranscriptIds field.
func (o *PtmFilter) SetTranscriptIds(v []string) {
	o.TranscriptIds = v
}

func (o PtmFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TranscriptIds) {
		toSerialize["transcriptIds"] = o.TranscriptIds
	}
	return json.Marshal(toSerialize)
}

type NullablePtmFilter struct {
	value *PtmFilter
	isSet bool
}

func (v NullablePtmFilter) Get() *PtmFilter {
	return v.value
}

func (v *NullablePtmFilter) Set(val *PtmFilter) {
	v.value = val
	v.isSet = true
}

func (v NullablePtmFilter) IsSet() bool {
	return v.isSet
}

func (v *NullablePtmFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePtmFilter(val *PtmFilter) *NullablePtmFilter {
	return &NullablePtmFilter{value: val, isSet: true}
}

func (v NullablePtmFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePtmFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


